name: "Build index.js for GitHub Action"
#TODO: Add a webhook to my action to trigger action action-main(exceute scan-dockerfile)
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - develop
      - feature/new-architecture
    paths-ignore:
      - "**.md"
      - "dist/**" # Evitar loop infinito
      - ".github/workflows/**"
      - ".gitignore"
      - ".vscode/**"
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Build the action
        run: npm run build

      - name: Commit and push built action
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add dist/
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "🤖 Update built action"
            git push
          fi

      - name: Upload built action
        uses: actions/upload-artifact@v4
        with:
          name: action
          path: dist
  test-execution:
    #TODO Make a matrix to run tests in parallel and use only steps. using variable
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Trigger test execution
        env:
          TOKEN: ${{ secrets.TOKEN_API_GIT }}
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $TOKEN" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/joao-pedro-rdo/teste-scan/dispatches \
            -d '{"event_type":"teste-da-api-on-demand-test"}'

      - name: ACtion-yaml
        env:
          TOKEN: ${{ secrets.TOKEN_API_GIT }}
          COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
          COMMIT_SHA: ${{ github.sha }}
          BRANCH: ${{ github.ref_name }}
        run: |
          EVENT_TYPE="teste-da-api-on-demand-$(date +'%Y%m%d-%H%M%S')"
          PAYLOAD=$(jq -n \
            --arg event_type "$EVENT_TYPE" \
            --arg commit "$COMMIT_MESSAGE" \
            --arg sha "$COMMIT_SHA" \
            --arg branch "$BRANCH" \
            '{event_type: $event_type, client_payload: {commit: $commit, sha: $sha, branch: $branch}}'
          )
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $TOKEN" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/joao-pedro-rdo/action-main/dispatches \
            -d "$PAYLOAD"
